### ISSUE TITLE
连接设备时异常,程序崩溃

### ISSUE THREAD

**Issue by fengfengfeng1234** [me2sy/MYScrcpy#1]
设备：OPPO Reno5 pro
android版本： 13

电脑设备： Apple M2 Pro

运行方式：直接运行代码

<img width="1190" alt="企业微信20240731-153444@2x" src="https://github.com/user-attachments/assets/cad5b9c8-d02c-4c12-bb71-7fb1e574072a">

**Comment by me2sy** [comment]
Mac系统对于sharememory文件名长度有31的限制，晚上更新一版，解决这个问题

**Comment by me2sy** [comment]
> 设备：OPPO Reno5 pro android版本： 13
> 
> 电脑设备： Apple M2 Pro
> 
> 运行方式：直接运行代码
> 
> <img alt="企业微信20240731-153444@2x" width="1190" src="https://private-user-images.githubusercontent.com/43661320/353738529-cad5b9c8-d02c-4c12-bb71-7fb1e574072a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MTk3NjEsIm5iZiI6MTcyMjQxOTQ2MSwicGF0aCI6Ii80MzY2MTMyMC8zNTM3Mzg1MjktY2FkNWI5YzgtZDAyYy00YzEyLWJiNzEtN2ZiMWU1NzQwNzJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDA5NTEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjNTE2ZTlmZDlmNTU4NDhkNGNlMDY5MWQ4NGIwNzQ3YzI3NjdlZTYyZTEzMTViM2ZhMDU1Mzg5NmY0ZDllZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pwB65-6-70yKjtuhh9XjMjIlCtD8caz2QqJ-YBxMMHw">

Mac系统对于sharememory文件名长度有31的限制，晚上更新一版，解决这个问题
