### ISSUE TITLE
1.1.0 运行可以显示 ui，但是 1.1.1 运行控制台无异常，无 ui 显示

### ISSUE THREAD

**Issue by fengfengfeng1234** [me2sy/MYScrcpy#2]
电脑设备： Apple M2 Pro
运行方式：直接运行代码

手机通过 usb 连接或者没有插入手机 都不行。
设备：OPPO Reno5 pro
android版本： 13

运行类型：
run() 或者 main()  

控制台统一显示：

pygame 2.6.0 (SDL 2.30.5, Python 3.11.9)
Hello from the pygame community. https://www.pygame.org/contribute.html

> requirements.txt 文件内容：

adbutils==2.7.2
annotated-types @ file:///home/conda/feedstock_root/build_artifacts/annotated-types_1716290248287/work
anyio @ file:///home/conda/feedstock_root/build_artifacts/anyio_1717693030552/work
apkutils2==1.0.0
av @ file:///Users/runner/miniforge3/conda-bld/av_1721561982857/work
certifi @ file:///home/conda/feedstock_root/build_artifacts/certifi_1720457958366/work/certifi
cffi==1.16.0
charset-normalizer==3.3.2
cigam==0.0.3
click @ file:///home/conda/feedstock_root/build_artifacts/click_1692311806742/work
dearpygui==1.11.1
decorator==5.1.1
deprecation==2.1.0
dnspython @ file:///home/conda/feedstock_root/build_artifacts/dnspython_1709190728464/work
easygui==0.98.3
email_validator @ file:///home/conda/feedstock_root/build_artifacts/email-validator-meta_1718984626658/work
exceptiongroup @ file:///home/conda/feedstock_root/build_artifacts/exceptiongroup_1720869315914/work
fastapi @ file:///home/conda/feedstock_root/build_artifacts/fastapi_1720998438716/work
fastapi-cli @ file:///home/conda/feedstock_root/build_artifacts/fastapi-cli_1716205772095/work
h11 @ file:///home/conda/feedstock_root/build_artifacts/h11_1664132893548/work
h2 @ file:///home/conda/feedstock_root/build_artifacts/h2_1634280454336/work
hpack==4.0.0
httpcore @ file:///home/conda/feedstock_root/build_artifacts/httpcore_1711596990900/work
httpx @ file:///home/conda/feedstock_root/build_artifacts/httpx_1708530890843/work
hyperframe @ file:///home/conda/feedstock_root/build_artifacts/hyperframe_1619110129307/work
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1713279365350/work
Jinja2 @ file:///home/conda/feedstock_root/build_artifacts/jinja2_1715127149914/work
loguru @ file:///Users/runner/miniforge3/conda-bld/loguru_1695547409960/work
markdown-it-py @ file:///home/conda/feedstock_root/build_artifacts/markdown-it-py_1686175045316/work
MarkupSafe @ file:///Users/runner/miniforge3/conda-bld/markupsafe_1706900210234/work
mdurl @ file:///home/conda/feedstock_root/build_artifacts/mdurl_1704317613764/work
numpy @ file:///Users/runner/miniforge3/conda-bld/numpy_1721965853053/work/dist/numpy-2.0.1-cp311-cp311-macosx_11_0_arm64.whl#sha256=dd8a18310942aa96e0fd89c0fe7ee524a7ab93cc9e458cbb5825d6cf957526e1
packaging==24.1
pillow @ file:///Users/runner/miniforge3/conda-bld/pillow_1719903580766/work
py==1.11.0
PyAudio==0.2.14
pycparser==2.22
pydantic @ file:///home/conda/feedstock_root/build_artifacts/pydantic_1720293063581/work
pydantic_core @ file:///Users/runner/miniforge3/conda-bld/pydantic-core_1720041227949/work
pyelftools==0.31
pyFLAC==3.0.0
pygame @ file:///Users/runner/miniforge3/conda-bld/pygame_1719378279440/work
Pygments @ file:///home/conda/feedstock_root/build_artifacts/pygments_1714846767233/work
python-multipart @ file:///home/conda/feedstock_root/build_artifacts/python-multipart_1707760088566/work
pyzmq @ file:///Users/runner/miniforge3/conda-bld/pyzmq_1715024416831/work
requests==2.32.3
retry==0.9.2
rich @ file:///home/conda/feedstock_root/build_artifacts/rich-split_1709150387247/work/dist
shellingham @ file:///home/conda/feedstock_root/build_artifacts/shellingham_1698144360966/work
sniffio @ file:///home/conda/feedstock_root/build_artifacts/sniffio_1708952932303/work
soundfile==0.12.1
starlette @ file:///home/conda/feedstock_root/build_artifacts/starlette-recipe_1709667058396/work
typer==0.12.3
typer-slim==0.12.3
typing_extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1717802530399/work
urllib3==2.2.2
uvicorn @ file:///Users/runner/miniforge3/conda-bld/uvicorn-split_1721483574005/work
xmltodict==0.13.0

**Comment by fengfengfeng1234** [comment]
老铁 你这个项目很强。

**Comment by me2sy** [comment]
> 老铁 你这个项目很不错。

感谢~
这个问题我一直在Win上开发使用，没有Mac，所有在Win上无法复现，今天试试Ubuntu
同时有以下思路：
1. 可以提供一下控制台运行日志 我看看情况
2. 试试 python -m myscrcpy.gui.dpg.window_devices 或 python -m myscrcpy.gui.dpg.window_video 看看能否调起GUI
3. 重新安装最新的 1.1.1 我又重传了一下

**Comment by fengfengfeng1234** [comment]
好滴，我晚上运行一下
