### ISSUE TITLE
【AI】关于yolo后续

### ISSUE THREAD

**Issue by fengfengfeng1234** [me2sy/MYScrcpy#3]
作者你好，基本上是把核心代码阅读完毕了，结构清晰，逻辑层次清晰。
但是 b 站和代码都没有动静了，别放弃。可以开启打赏功能。支持一杯 coffee

期待后续 yolo ai 加入

**Comment by me2sy** [comment]
你好，感谢你的支持与鼓励！
实在抱歉，本周工作繁忙，业余时间少的可怜~
项目还有好多好多功能要做，时间精力允许的话会一直做下去。这两天每天熬夜也会抽出2~3个小时在MYS上。请放心！
目前在憋一个大的！正重构开发新一代DPG界面，希望给你和大家带来实用、好用、好玩的工具，或者未来说是平台。敬请期待！
因个人时间能力有限，使用中有任何问题，请多多包涵，我也将尽快改正。
最后再次感谢对本项目的关注~！
（这个issue等YOLO实现了我来关，哈哈，不过YOLO优先级不高，得先等上一段）

**Comment by loveanao** [comment]
加油！

**Comment by me2sy** [comment]
YOLO简单记牌器及教程已发~欢迎继续拓展
https://blog.csdn.net/weixin_43463913/article/details/142712201
