### ISSUE TITLE
nicegui headless in docker container?

### ISSUE THREAD

**Issue by frostworx** [me2sy/MYScrcpy#4]
Hello,
foremost thank you very much for all your work on this very interesting project!
I discovered it just a few days ago by chance and it is already very impressive how far you proceed!

My idea is to use the nicegui web mode embedded (via ingress) in home assistant, so I could control a mobile device attached to my home assistant machine via usb remotely. It would be great to have the possibility to control devices, which have no native support _(maybe even with some automated input methods to start the proprietary apps automatically and/or ocr for their sensor outputs)_

I already created a _(quick and dirty)_ docker container for myscrcpy and adb sees the mobile device within the container.

Starting the nicegui via `python3 ./lib/python3.11/site-packages/myscrcpy/gui/ng/demo.py ` works as well and

http://localhomeassistantip:51000 
 is reachable from the network.

I only get a blank white screen here though, so I'd like to ask if this is expected behavior or if there is something I could do
(with previously started commands) to enable the connection to the mobile device?

_(when stopping the demo.py process, the web ui complains with "Connection lost. Trying to reconnect...", so basically it seems to work)_

Would be great if you could help.

I wish you much fun and great success with myscrcpy!

**Comment by me2sy** [comment]
I'm glad to heard that you used MYScrcpy to implement your ingenious idea And thank you for that.
A New Web GUI (DEMO) is made today. Just cmd  **'python -m myscrcpy.gui.ng.main'** and enjoy.
My apologize, but the main focus is currently on automation and the PC version. The WEB GUI is somewhat rough. 
You can try optimizing it; the structure is designed to be very simple.
（the old one was designed to show how to share frame in memoryview，Use VideoStream And ZMQ to Share Video and Control）
Notice that everyone in you network will SEE the device by visit url http://xxx:51000/vsc/frame/{your_device_serial} 
consider set a password or a auth by yourself.
Please feel free to provide feedback at any time.
![Nicegui_DEMO](https://github.com/user-attachments/assets/a012f0b9-3d21-43a5-80a2-15be51668e92)

**Comment by frostworx** [comment]
Oh wow! Thank you very much for your reply and for the new web gui demo!
Can't wait to test it - and will report back as soon as possible.

Of course I totally understand that your main focus is on the PC gui functionality and I'm already very grateful for what you even implemented with the web gui.

The [scrcpy-ws ](https://github.com/NetrisTV/ws-scrcpy) project also offers web ui control over scrcpy, but it is based on a custom forked scrcpy 1.x version, so I think your approach is much better for my needs.

 I'm not too experienced with writing bigger python code, so I'm not sure if I can make useful modifications myself,
but I'll try when I find the time.

Also thank you very much for raising the security concerns! I'll be cautious :)

**Comment by frostworx** [comment]
Yaaay, just tried it and it *just works* (without home assistant so far ;)). Thank you SO MUCH!!!

**Comment by me2sy** [comment]
> Yaaay, just tried it and it _just works_ (without home assistant so far ;)). Thank you SO MUCH!!!
> 
> **editing** (to avoid another email):
> 
> A quick and dirty attempt to get it into home assistant using the [hass_ingress](https://github.com/lovelylain/hass_ingress) integration _(via HACS)_ failed - the main windows complains with "Connection lost. Trying to reconnect.." and directly calling the /device/mobileid url doesn't render anything. I'll try if I can make it work and report back soonish.
> 
> edit: sorry, I didn't have the opportunity to look into it (understanding what needs to be done ingress wise is the core problem here - I simply don't know anything about it :)), but impressive how fast you proceed - I wished I could give you another star :) thank you so much for your amazing work _(I do not even use a mobile device regulary btw ;))_

Update 1.5.5 with new structure, hope can help you a little

**Comment by frostworx** [comment]
Thank you very much! I didn't get the opportunity recently to look into this again, but will for sure follow your project. I recently found a home assistant firefox addon, which might already be enough for my needs.
Please keep up your great work and have much fun with working on it!

**Comment by Migsi** [comment]
@frostworx mind sharing your current docker file? I'd love to look into polishing it a little and contribute it to the project via PR if you're fine with it.

**Comment by frostworx** [comment]
@Migsi 
sure (there's not much to see here though, and I can't guarantee that this is the last working state I tried above):

```
# cat Dockerfile 
  FROM ubuntu:24.04
  COPY run.sh /run.sh
  RUN chmod +x /run.sh
  RUN apt-get update -y
  RUN apt-get upgrade -y
  RUN apt -y install build-essential python3-dev ffmpeg libavcodec-extra portaudio19-dev pip adb iputils-ping iproute2 netcat-openbsd
  RUN pip3 install mysc[web] --break-system-packages 
  EXPOSE 51000
  CMD ["/run.sh"]
```

Good luck and have fun! 😄 

EDIT:

forgot

```
# cat run.sh 
#!/bin/bash
echo "Container started successfully!"
/data/local.sh

```

```
# cat mydata/local.sh 
#!/bin/bash
while ! echo exit | nc -vzw1 redroid 5555; do sleep 1; done
adb connect redroid:5555
```
