### ISSUE TITLE
系统资源占用高

### ISSUE THREAD

**Issue by loveanao** [me2sy/MYScrcpy#6]
大佬，跑了2天
再对比QTScrcpy后，
发现MyScrcpy再系统资源占用上,总体要高4倍的样子，

链接同款手机和输出分辨率，
我的硬件配置，i7 6950x 10核@4Ghz + 64GB DDR4 3200 + RTX2080 TI 22GB

启用DearPyGui 界面

QTScrcpy对系统资源占用再5-6%
（CPU占用基总体占用5%，显卡资源占用5%）

MyScrcpy对系统资源占用再15-24%
（CPU占用基本一个核心占满，总体占用10%，显卡核心3D资源占用15-18%，显存时间长了会飙升1.5GB）

CPU占用
![1725415815595](https://github.com/user-attachments/assets/842b82bf-64b3-41bf-b914-776f7d059fa5)

GPU占用
![0dc7ec7e0ac07f22f92555f213a596a1](https://github.com/user-attachments/assets/0eff67d0-0a9a-469b-952f-d0837c3ea734)

所有请教大佬如何优化

跑久了电脑风扇就开始嗷嗷叫了。

后续想加上yolo目标识别，完成辅助，那就很吃电脑硬件了

**Comment by me2sy** [comment]
QTScrcpy是一个很优秀的项目，采用C++，性能上具有先天优势。
本来也考虑过用 qtside6来做，但一想到做重了，就选了 DPG :hand_over_mouth:
你是一直连续跑了两天么？运行多久出现这个情况？
判断有可能是 Dearpygui 框架的问题，也可能是某些资源没释放。我也再观察观察。

**Comment by me2sy** [comment]
> 大佬，跑了2天 再对比QTScrcpy后， 发现MyScrcpy再系统资源占用上,总体要高4倍的样子，
> 
> 链接同款手机和输出分辨率， 我的硬件配置，i7 6950x 10核@4Ghz + 64GB DDR4 3200 + RTX2080 TI 22GB
> 
> 启用DearPyGui 界面
> 
> QTScrcpy对系统资源占用再5-6% （CPU占用基总体占用5%，显卡资源占用5%）
> 
> MyScrcpy对系统资源占用再15-24% （CPU占用基本一个核心占满，总体占用10%，显卡核心3D资源占用15-18%，显存时间长了会飙升1.5GB）
> 
> CPU占用 ![1725415815595](https://private-user-images.githubusercontent.com/11850710/364199365-842b82bf-64b3-41bf-b914-776f7d059fa5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NDIwNzgsIm5iZiI6MTcyNTQ0MTc3OCwicGF0aCI6Ii8xMTg1MDcxMC8zNjQxOTkzNjUtODQyYjgyYmYtNjRiMy00MWJmLWI5MTQtNzc2ZjdkMDU5ZmE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDA5MjI1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwZjNlMDgyZDZmNDczM2EwMzE5MzgzOTQ3ZmZjNTUyNmQwYzVlNGQ4Yjk4ZWU4NDdjMmZmNGM3MDRlMDYwOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mLOTgxKQgCmbYr8t6ep3KuumWh5QZkY9bbDOocpkBNI)
> 
> GPU占用 ![0dc7ec7e0ac07f22f92555f213a596a1](https://private-user-images.githubusercontent.com/11850710/364200895-0eff67d0-0a9a-469b-952f-d0837c3ea734.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NDIwNzgsIm5iZiI6MTcyNTQ0MTc3OCwicGF0aCI6Ii8xMTg1MDcxMC8zNjQyMDA4OTUtMGVmZjY3ZDAtMGE5YS00NjliLTk1MmYtZDA4MzdjM2VhNzM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDA5MjI1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjOTkwODNiYWZiMjljZmI2NDhiODdlYTM3N2E3MTdjYjQxMWEyZmI2ZDhkYmNkN2Q5YTY0Mzk3NTBjZjc5ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YZ91TBMtJq-tpoKx78IT6Wz7tgXKWxKnmxJMhFiYX8w)
> 
> 所有请教大佬如何优化
> 
> 跑久了电脑风扇就开始嗷嗷叫了。
> 
> 后续想加上yolo目标识别，完成辅助，那就很吃电脑硬件了

其实你也可以换个思路🤭
仅使用 myscrcpy.core 使用VideoAdapter获取图像，通过controlAdapter进行控制
然后开一个QTScrcpy 做监控界面就行了

**Comment by loveanao** [comment]
> QTScrcpy是一个很优秀的项目，采用C++，性能上具有先天优势。 本来也考虑过用 qtside6来做，但一想到做重了，就选了 DPG 🤭 你是一直连续跑了两天么？运行多久出现这个情况？ 判断有可能是 Dearpygui 框架的问题，也可能是某些资源没释放。我也再观察观察。

我个人感觉也是UI框架的问题，
我用MyScrcpy控制手机，
累计玩了累7-8个小时的手游。
玩到半个小时的时候发现风扇嗷嗷叫了。

查看资源管理器，资源占用上来了。

5开游戏的PC客户端。
也才达到MyScrcpy开一个的资源占用。
所以就来这里给你反馈一下。
我也来陆陆续续深入研究一下

我其实就是想自己在多开手游端，
队长号手动，队员号就用这个实现一些辅助工作，
这样效率就高很多，

**Comment by me2sy** [comment]
> > QTScrcpy是一个很优秀的项目，采用C++，性能上具有先天优势。 本来也考虑过用 qtside6来做，但一想到做重了，就选了 DPG 🤭 你是一直连续跑了两天么？运行多久出现这个情况？ 判断有可能是 Dearpygui 框架的问题，也可能是某些资源没释放。我也再观察观察。
> 
> 我个人感觉也是UI框架的问题， 我用MyScrcpy控制手机， 累计玩了累7-8个小时的手游。 玩到半个小时的时候发现风扇嗷嗷叫了。
> 
> 查看资源管理器，资源占用上来了，直接将我一个4Ghz的核心干满了。
> 
> 5开游戏的PC客户端。 也才达到MyScrcpy开一个的资源占用。 所以就来这里给你反馈一下。 我也来陆陆续续深入研究一下
> 
> 我其实就是想自己在多开手游端， 队长号手动，队员号就用这个实现一些辅助工作， 这样效率就高很多，

明白了，这个场景挺有意思~
我找机会也长时间运行一下，看看什么情况。之前用pygame几个小时，也没太大问题。估计是dpg的事儿。

**Comment by loveanao** [comment]
> > > QTScrcpy是一个很优秀的项目，采用C++，性能上具有先天优势。 本来也考虑过用 qtside6来做，但一想到做重了，就选了 DPG 🤭 你是一直连续跑了两天么？运行多久出现这个情况？ 判断有可能是 Dearpygui 框架的问题，也可能是某些资源没释放。我也再观察观察。
> > 
> > 
> > 我个人感觉也是UI框架的问题， 我用MyScrcpy控制手机， 累计玩了累7-8个小时的手游。 玩到半个小时的时候发现风扇嗷嗷叫了。
> > 查看资源管理器，资源占用上来了，直接将我一个4Ghz的核心干满了。
> > 5开游戏的PC客户端。 也才达到MyScrcpy开一个的资源占用。 所以就来这里给你反馈一下。 我也来陆陆续续深入研究一下
> > 我其实就是想自己在多开手游端， 队长号手动，队员号就用这个实现一些辅助工作， 这样效率就高很多，
> 
> 明白了，这个场景挺有意思~ 我找机会也长时间运行一下，看看什么情况。之前用pygame几个小时，也没太大问题。估计是dpg的事儿。

刚刚简单做了测试，

视频帧播放，
使用cv2展示后，GPU占用率从 Dearpygui 的raw_texture 从 16%下降到 8-10%


CPU一个核心满载一个是AV解码导致的。

**Comment by loveanao** [comment]
> > > QTScrcpy是一个很优秀的项目，采用C++，性能上具有先天优势。 本来也考虑过用 qtside6来做，但一想到做重了，就选了 DPG 🤭 你是一直连续跑了两天么？运行多久出现这个情况？ 判断有可能是 Dearpygui 框架的问题，也可能是某些资源没释放。我也再观察观察。
> > 
> > 
> > 我个人感觉也是UI框架的问题， 我用MyScrcpy控制手机， 累计玩了累7-8个小时的手游。 玩到半个小时的时候发现风扇嗷嗷叫了。
> > 查看资源管理器，资源占用上来了，直接将我一个4Ghz的核心干满了。
> > 5开游戏的PC客户端。 也才达到MyScrcpy开一个的资源占用。 所以就来这里给你反馈一下。 我也来陆陆续续深入研究一下
> > 我其实就是想自己在多开手游端， 队长号手动，队员号就用这个实现一些辅助工作， 这样效率就高很多，
> 
> 明白了，这个场景挺有意思~ 我找机会也长时间运行一下，看看什么情况。之前用pygame几个小时，也没太大问题。估计是dpg的事儿。

经过测试
H264码流解码 pyav 应该是使用了软解，
是CPU占用核心高的原因
https://stackoverflow.com/questions/71535857/is-there-any-hardware-decoding-or-encoding-when-reading-video-stream-byte-in-pya


通过pypi安装的 pyav 好像目前不支持 ffmpeg 使用 h264_cuvid 指令进行 GPU硬解

只能通过本地编译安装pyav，我暂未测试
https://blog.csdn.net/qq_43260356/article/details/136915692

**Comment by me2sy** [comment]
> > > > QTScrcpy是一个很优秀的项目，采用C++，性能上具有先天优势。 本来也考虑过用 qtside6来做，但一想到做重了，就选了 DPG 🤭 你是一直连续跑了两天么？运行多久出现这个情况？ 判断有可能是 Dearpygui 框架的问题，也可能是某些资源没释放。我也再观察观察。
> > > 
> > > 
> > > 我个人感觉也是UI框架的问题， 我用MyScrcpy控制手机， 累计玩了累7-8个小时的手游。 玩到半个小时的时候发现风扇嗷嗷叫了。
> > > 查看资源管理器，资源占用上来了，直接将我一个4Ghz的核心干满了。
> > > 5开游戏的PC客户端。 也才达到MyScrcpy开一个的资源占用。 所以就来这里给你反馈一下。 我也来陆陆续续深入研究一下
> > > 我其实就是想自己在多开手游端， 队长号手动，队员号就用这个实现一些辅助工作， 这样效率就高很多，
> > 
> > 
> > 明白了，这个场景挺有意思~ 我找机会也长时间运行一下，看看什么情况。之前用pygame几个小时，也没太大问题。估计是dpg的事儿。
> 
> 经过测试 通过pypi安装的 pyav 好像目前不支持 ffmpeg 使用 h264_cuvid 指令进行 GPU硬解 默认是使用了软解，是CPU核心占用高的原因
> 
> https://stackoverflow.com/questions/71535857/is-there-any-hardware-decoding-or-encoding-when-reading-video-stream-byte-in-pya
> 
> https://cloud.tencent.com/developer/ask/sof/106818209
> 
> 解决方案 1：只能通过本地编译安装pyav，我暂未测试 https://blog.csdn.net/qq_43260356/article/details/136915692 2：使用DeFFcode 我暂未测试

收到 我好好研究一下，看看有没有办法进行优化
感谢你的钻研和付出:thumbsup:，辛苦了兄弟
我有方案了第一时间告诉你

**Comment by loveanao** [comment]
> > > > > QTScrcpy是一个很优秀的项目，采用C++，性能上具有先天优势。 本来也考虑过用 qtside6来做，但一想到做重了，就选了 DPG 🤭 你是一直连续跑了两天么？运行多久出现这个情况？ 判断有可能是 Dearpygui 框架的问题，也可能是某些资源没释放。我也再观察观察。
> > > > 
> > > > 
> > > > 我个人感觉也是UI框架的问题， 我用MyScrcpy控制手机， 累计玩了累7-8个小时的手游。 玩到半个小时的时候发现风扇嗷嗷叫了。
> > > > 查看资源管理器，资源占用上来了，直接将我一个4Ghz的核心干满了。
> > > > 5开游戏的PC客户端。 也才达到MyScrcpy开一个的资源占用。 所以就来这里给你反馈一下。 我也来陆陆续续深入研究一下
> > > > 我其实就是想自己在多开手游端， 队长号手动，队员号就用这个实现一些辅助工作， 这样效率就高很多，
> > > 
> > > 
> > > 明白了，这个场景挺有意思~ 我找机会也长时间运行一下，看看什么情况。之前用pygame几个小时，也没太大问题。估计是dpg的事儿。
> > 
> > 
> > 经过测试 通过pypi安装的 pyav 好像目前不支持 ffmpeg 使用 h264_cuvid 指令进行 GPU硬解 默认是使用了软解，是CPU核心占用高的原因
> > https://stackoverflow.com/questions/71535857/is-there-any-hardware-decoding-or-encoding-when-reading-video-stream-byte-in-pya
> > https://cloud.tencent.com/developer/ask/sof/106818209
> > 解决方案 1：只能通过本地编译安装pyav，我暂未测试 https://blog.csdn.net/qq_43260356/article/details/136915692 2：使用DeFFcode 我暂未测试
> 
> 收到 我好好研究一下，看看有没有办法进行优化 感谢你的钻研和付出，辛苦了兄弟！ 👍 我有方案了第一时间告诉你

嗯，加油，因为我看QTScrcpy 也是使用FFmpeg进行的解码操作，没理由，MyScrcpy解码吃那么多CPU资源。就算有性能差异，也不至于差那么多。

**Comment by me2sy** [comment]
> > 收到 我好好研究一下，看看有没有办法进行优化 感谢你的钻研和付出，辛苦了兄弟！ 👍 我有方案了第一时间告诉你
> 
> 嗯，加油，因为我看QTScrcpy 也是使用FFmpeg进行的解码操作，没理由，MyScrcpy解码吃那么多CPU资源。就算有性能差异，也不至于差那么多。

研究了一下
dpg中 raw 和 static 使用的是 1D rgb 0...1 float32 推测这个是GPU占用的主要原因（目前GPU只3D运算，并不占用GPU内存）
不同的max_size 占用GPU 3D运算的资源不同

而CPU推测为 之前调用的是 av.VideoFrame.to_ndarray() 返回 3D rgb 0...255 uint8
在原转换过程占用CPU较高  时间也耗在 .astype(np.float32) / 255 上了

针对CPU 本次优化了转换过程 但并不完美
GPU目前看只能等imgui及DPG有动作了，或者换GUI架构，或者调低 max_size

目前就这样了，之后有时间再观察看看有没有更好的办法 ffmpeg 软硬解码 这个也是一个研究的方向
